### ISSUE TITLE
Kronos stv game not loading on start

### ISSUE THREAD

**Issue by regbox80** [FCare/Kronos#1454] opened 2023-02-27 16:04 UTC
Having stv game diehard on Rom cartridge selected and it runs. When exiting emulator it saves diehard as selected cartridge. When now starting again kronos.exe I first need to open settings (without need to do anything there, just open settings and close) and then I can start emulation. If I do not first open settings and just start kronos.exe and click emulate, the emulator will not load the game and shows error. 
Standalone version 2. 5.0
Windows 10

What's the full name of the game (including region) ?

What's your frontend ? (standalone, libretro, ...) ?

What's your OS ? (windows, linux, OSX, ...) ?

What's your hardware ? (CPU, GPU, ...) ?

What's the storage type of the game (official cd, burned cd or cd image) ?

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)

Are you using any setting different from default ? If so, precise

Did this game work previously ? Do you remember when ? Is it happening with other games ?

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this

**Comment by fafling** [comment] 2023-03-01 00:11
Duplicate of #1277

**Closed as completed** 2024-11-30 13:18 UTC
