### ISSUE TITLE
Gungriffon:  Ground Textures Missing

### ISSUE THREAD

**Issue by gridmortis** [FCare/Kronos#1433] opened 2023-02-06 01:45 UTC
Gungriffon (USA)

Retroarch

Windows 10 Home

 i9-11900KB, RTX 3060ti, 32gb ram

CD Image

Cue/Bin

Default Settings (I tried all settings in options without change in the issue.)

Unsure if earlier versions of emulator had same issue.  It is also happening with the sequel, Gungriffon 2 (Jap).

![Gungriffon-230205-190251](https://user-images.githubusercontent.com/121533572/216863045-f19a1316-db92-49d1-a5f1-eaa83500c58f.png)

**Comment by fafling** [comment] 2023-02-07 23:55
Duplicate of #1281

**Closed as completed** 2023-02-08 00:14 UTC
