### ISSUE TITLE
Deep Fear - PAL - Kronos 2,15

### ISSUE THREAD

**Issue by Pointer1992** [FCare/Kronos#970] opened 2020-12-27 10:50 UTC
![86268934-480f3c00-bbc9-11ea-92f7-cca09e8da749](https://user-images.githubusercontent.com/6630292/103169114-51f0bf80-4839-11eb-9832-ac72f300a584.jpg)
![86268937-48a7d280-bbc9-11ea-874c-b44107f16c7f](https://user-images.githubusercontent.com/6630292/103169115-5321ec80-4839-11eb-9fee-cec07111190f.jpg)
![86268942-49d8ff80-bbc9-11ea-9a3c-6b0e2633b400](https://user-images.githubusercontent.com/6630292/103169117-5321ec80-4839-11eb-95b0-2a3e0709b210.jpg)

NBG0 mode
8-bit(256 colors)
Tile(1H x 1V)
Plane Size = 1H x 1V
Pattern Name data size = 1 word
Character Number Supplement bit = 0
Special Priority bit = 0
Special Color Calculation bit = 0
Supplementary Palette number = 0
Supplementary Color number = 12
Plane A Address = 00076000
Plane B Address = 00076000
Plane C Address = 00076000
Plane D Address = 00076000
Screen Scroll x = 0, y = 0
Coordinate Increments x = 1.000000, y = 1.000000
Window W0 Enabled:
Horizontal start = 0
Vertical start = 16
Horizontal end = 319
Vertical end = 239
Display inside of Window
Window Overlap Logic: OR
Color Ram Address Offset = 0
Priority = 7
Color Offset A Enabled
R = 0, G = 0, B = 0
Special Color Calculation 0

8-bit(256 colors)
Tile(1H x 1V)
Plane Size = 1H x 1V
Pattern Name data size = 1 word
Character Number Supplement bit = 0
Special Priority bit = 0
Special Color Calculation bit = 0
Supplementary Palette number = 1
Supplementary Color number = 0
Plane A Address = 00014000
Plane B Address = 00014000
Plane C Address = 00014000
Plane D Address = 00014000
Screen Scroll x = -8, y = -504
Coordinate Increments x = 1.000000, y = 1.000000
Window W0 Enabled:
Horizontal start = 0
Vertical start = 16
Horizontal end = 319
Vertical end = 239
Display inside of Window
Window Overlap Logic: OR
Color Ram Address Offset = 0
Priority = 1
Color Offset B Enabled
R = 0, G = 0, B = 0
Special Color Calculation 0

8-bit(256 colors)
Tile(1H x 1V)
Plane Size = 1H x 1V
Pattern Name data size = 1 word
Character Number Supplement bit = 0
Special Priority bit = 0
Special Color Calculation bit = 0
Supplementary Palette number = 3
Supplementary Color number = 8
Plane A Address = 00018000
Plane B Address = 00018000
Plane C Address = 00018000
Plane D Address = 00018000
Screen Scroll x = -496, y = -488
Window W0 Enabled:
Horizontal start = 0
Vertical start = 16
Horizontal end = 319
Vertical end = 239
Display inside of Window
Window Overlap Logic: OR
Color Ram Address Offset = 0
Priority = 7
Color Offset B Enabled
R = 0, G = 0, B = 0
Special Color Calculation 0

Border Color Mode = Back screen
Display Resolution = 320 x 256(NTSC)
Interlace Mode = Non-Interlace
Latches HV counter when external latch flag is read
H Counter = 0
V Counter = 248
Line Color Screen Stuff

Mode = Single color
Address = 05E00000
Back Screen Stuff

Mode = Single color
Address = 05E7FFFE
Color Offset A Enabled
R = 0, G = 0, B = 0
Sprite Stuff

Sprite Type = 7
VDP1 Framebuffer Data Format = RGB and palette
Sprite Window Enabled
Window W0 Enabled:
Horizontal start = 0
Vertical start = 16
Horizontal end = 319
Vertical end = 239
Display inside of Window
Window Overlap Logic: OR
Color RAM Offset = 0
Priority 0 = 2
Priority 1 = 0
Priority 2 = 5
Priority 3 = 5
Priority 4 = 5
Priority 5 = 5
Priority 6 = 5
Priority 7 = 5
Color Offset B Enabled
R = 0, G = 0, B = 0

**Comment by fafling** [comment] 2020-12-28 22:19
Duplicate of #559 .
The trailing and missing graphics with real bios seems to be due to a bug that prevent the processing of the beginning of VDP1 command list in Deep fear. The first commands are missing in VDP1 debug screen in real bios, while they are present with emulated bios.
The erasure scaled sprite command is one of the missing commands. Moreover, since #559 was created, there has been a change in Kronos VDP1 erase/write emulation which now prevents the automatic erasure of the framebuffer in Deep fear. So nothing erases the framebuffers which explains the trailing graphics.

**Comment by Pointer1992** [comment] 2021-01-19 11:11
> Duplicate of #559 .
> The trailing and missing graphics with real bios seems to be due to a bug that prevent the processing of the beginning of VDP1 command list in Deep fear. The first commands are missing in VDP1 debug screen in real bios, while they are present with emulated bios.
> The erasure scaled sprite command is one of the missing commands. Moreover, since #559 was created, there has been a change in Kronos VDP1 erase/write emulation which now prevents the automatic erasure of the framebuffer in Deep fear. So nothing erases the framebuffers which explains the trailing graphics.
Video = OK 
Audio = Bug 
https://www.youtube.com/watch?v=t54f-CH3TxA&feature=youtu.be
Deep Fear PAL Version 
Kronos - Retroarch 

The original kronos does not allow you to record materials with Bandicam and mirillis action

**Comment by barbudreadmon** [comment] 2021-01-19 13:18
> The original kronos does not allow you to record materials with Bandicam and mirillis action

I think you would need something that record gpu output, iirc recent gpus have functions like this incorporated in their "tools" (pretty sure i've seen something like this in Nvidia's Geforce Experience at the very least), otherwise you can still use 3rd party tools like Fraps i guess.

Disclaimer : the libretro kronos core is 10 commits behind, so there are discrepancies between standalone and libretro atm, not sure they'll affect Deep Fear though

**Comment by Pointer1992** [comment] 2021-01-19 14:48
> 
> 
> > The original kronos does not allow you to record materials with Bandicam and mirillis action
> 
> I think you would need something that record gpu output, iirc recent gpus have functions like this incorporated in their "tools" (pretty sure i've seen something like this in Nvidia's Geforce Experience at the very least), otherwise you can still use 3rd party tools like Fraps i guess.
> 
> Disclaimer : the libretro kronos core is 10 commits behind, so there are discrepancies between standalone and libretro atm, not sure they'll affect Deep Fear though


https://www.youtube.com/watch?v=orySEszNebY&feature=youtu.be
 original kronos video

**Comment by fafling** [comment] 2021-01-19 20:14
Yes, like I said, that's the display problem with real bios described in #559 .
The display with emulated bios has been fixed with a recent commit, see #971.

**Comment by Pointer1992** [comment] 2021-01-19 20:50
> 
> 
> Yes, like I said, that's the display problem with real bios described in #559 .
> The display with emulated bios has been fixed with a recent commit, see #971.


https://www.youtube.com/watch?v=P3MsiSblY84&feature=youtu.be
Orginal Kronos emulator - Audio/Video bug 
Kronos Retroarch - Audio bug

**Comment by fafling** [comment] 2021-01-19 21:24
Missing sprites in emulated bios is what #971 is about.
The sound glitch is listed in #556.

**Comment by BenjaminSiskoo** [comment] 2022-11-16 11:18
Fixed with https://github.com/FCare/Kronos/commit/8328b5ebdb2505607a301a45068150d5c354b8af

**Closed as completed by BenjaminSiskoo** 2022-11-16 11:18 UTC

**Comment by duke912** [comment] 2024-11-23 16:14
The bug still persist on the kronos core for retroarch

**Comment by BenjaminSiskoo** [comment] 2024-11-23 16:18
With USA, the problem is still there
