### ISSUE TITLE
Deep Fear black screen after start

### ISSUE THREAD

**Issue by Anths2016** [FCare/Kronos#745] opened 2020-01-17 13:11 UTC
Black screen after start game.

**Comment by barbudreadmon** [comment] 2020-01-18 11:02
Duplicate of https://github.com/FCare/Kronos/issues/559. This game has some known issues in kronos (especially with real bios, it's probably the only game where using HLE bios is recommended), the black screen is normally a fmv, you can skip it by pressing start.

**Comment by FCare** [comment] 2020-01-22 21:11
duplicate

**Closed as completed** 2020-01-22 21:11 UTC
