### ISSUE TITLE
Mouse/Gun support appears non functional?

### ISSUE THREAD

**Issue by wiesshund** [FCare/Kronos#968] opened 2020-12-20 04:50 UTC
You can configure the mouse as a controller, and set all it's buttons and the axis
you can also set it as a gun, and configure the axis and buttons for that

but it does not seem to actually respond in any game
not even clicking the start button or anything

Does not appear to be capturing mouse movement or button input at all inside the emulator
when it is running even though it can see it during input configuration fine
Even in full screen

**Comment by BenjaminSiskoo** [comment] 2020-12-20 10:58
Standalone or Retroarch ?

**Comment by wiesshund** [comment] 2020-12-20 11:01
Standalone download from the website
2.1.3 64bit

**Comment by BenjaminSiskoo** [comment] 2020-12-20 11:11
Ok, François is busy, for few months, so it will take times to get this work. Thanks for your report. :)

**Comment by wiesshund** [comment] 2020-12-20 11:33
Looks like this was built on 8/12/2020
and i see a commit for mouse support dated only about 5 days ago

Website only offers one download, labeled 2.1.1, but the build it gives is 2.1.3

Not that big of a deal, just happened that the only saturn disc i had handy to test it with was virtua cop
does not work very good with analog controls

Kronos does, the game doesn't LOL

Graphics look pretty good though

**Comment by barbudreadmon** [comment] 2020-12-20 17:40
> and i see a commit for mouse support dated only about 5 days ago

That was for the libretro port, i believe mouse support has been broken on standalone for a long time

**Comment by wiesshund** [comment] 2020-12-21 05:33
well, that be a bummer

**Comment by fafling** [comment] 2022-03-12 11:21
Duplicate of #921

**Comment by BenjaminSiskoo** [comment] 2022-11-16 11:19
Mouse support is ok, need to wait the next release

**Closed as completed by BenjaminSiskoo** 2022-11-16 11:19 UTC
