### ISSUE TITLE
[Dark Savior] Title screen and character shadow glitch

### ISSUE THREAD

**Issue by ner00** [FCare/Kronos#883] opened 2020-05-17 21:59 UTC
**Title screen glitch**
The title screen should show a mountain without the game title, and a few seconds later the title is dropped into the mountain. In Kronos, the title appears immediately before the animation ever drops it. This issue was already present in the previous version. Here you can see the issue mentioned above (as it should be, I mean): https://youtu.be/Ht_AAC8kw5s?t=24

**(Character) Shadow glitch**
This glitch seems to have been introduced in recent development since it was not present in the previous version. The shadows under the characters are dark and flickering, they should be a tad lighter and not flickering, like this: https://youtu.be/Ht_AAC8kw5s?t=427

**Comment by fafling** [comment] 2020-05-18 15:05
The title screen problem is visible with both video cores, both in last WIP and public v2.1.2. The title is displayed by NBG0. In VDP2 debug window, I don't see anything that should make the title invisible before it is zoomed. It could be a problem caused by the lack of cycle pattern emulation in Kronos.

The flickering shadow problem appears in the may 7th WIP, only in the OpenGL core. The shadow is drawn by VDP1 with half-transparency. The shadow indeed becomes darker in that WIP when it's visible (left public v2.1.2, right last WIP of may 18th) :
![image](https://user-images.githubusercontent.com/7624262/82228108-fb2d1a00-9928-11ea-81d6-d9aa1c1b4c45.png)
Save state :
[dark_savior_ingame.zip](https://github.com/FCare/Kronos/files/4644888/dark_savior_ingame.zip)
It's a general problem and concerns VDP1's RGB shadow and half transparency. You can also see it at the first dialog of Mystaria which has both effects.

Tested with the US CD.

**Comment by ner00** [comment] 2020-05-18 15:16
> You can also see it at the first dialog of Mystaria which has both effects

I am not sure if this may be related, but the Policenauts main menu also has some transparency flickering. It's possible that it is related. I haven't had the chance to test with a previous version, will try to do that later.

**Comment by fafling** [comment] 2020-05-18 15:21
Yes it's the same problem, the menu uses VDP1 half-transparency.

**Comment by FCare** [comment] 2020-05-18 15:54
transparency is fixed by 85fb9a94660c0babccec798188527006385389cb

Title is linked to Cycle pattern which is missing and highly complicated to integrate.

**Comment by ner00** [comment] 2020-05-18 17:23
> transparency is fixed by [85fb9a9](https://github.com/FCare/Kronos/commit/85fb9a94660c0babccec798188527006385389cb)

Great.

> Title is linked to Cycle pattern which is missing and highly complicated to integrate.

It's not big deal in this case, and I'm assuming that other games also aren't affected in a big way by the lack of cycle pattern calculation, correct?

**Comment by fafling** [comment] 2020-05-18 23:07
The worst case scenario is an NBG layer that shouldn't display if cycle pattern where emulated, and that covers the screen, like in Braindead 13, see #209. The workaround is simple : disable the display of that NBG layer.

**Comment by fafling** [comment] 2020-05-19 14:12
I confirm the problem of half transparency and shadow are fixed in the last WIP.

**Comment by ner00** [comment] 2020-05-24 14:04
> The title screen problem is visible with both video cores, both in last WIP and public v2.1.2. The title is displayed by NBG0. In VDP2 debug window, I don't see anything that should make the title invisible before it is zoomed. It could be a problem caused by the lack of cycle pattern emulation in Kronos.

@fafling Is the cycle pattern emulation also lacking from Yabause? I ask this because in Yabause core the title screen animation plays correctly; in YabaSanshiro it plays incorrectly also. Also, unsure if related but a changelog from SSF emulator mentions the following:

> **Dark Savior:** Enable "Bus Wait" (fix for logo).

or rather this:

> ダークセイバー
    Bus Waitにチェック（ロゴ）

**Comment by fafling** [comment] 2020-05-24 16:58
@ner00 Indeed, the bug seems to date from Kronos 1.0.0.

I didn't understood the debug display of Kronos for the title before it is zoomed :
![image](https://user-images.githubusercontent.com/7624262/82759617-d6381b80-9dee-11ea-8144-3554019c0df1.png)
It shows both coordinate increments with "inf" value. This corresponds to infinity. Actually, Kronos doesn't display the coordinate increments as VDP2 manual defines them, but their opposite which is the zoom ratio. So it means that the actual coordinate increment is 0. @FCare Do you confirm that ?

In that case, it's outside of the range allowed for NBG zoom, as the zoom ratio is limited to 256 (VDP2 manual p. 6, "Scale function" in table 1.4) which corresponds to the coordinate increment fractional register set with 1 in the LSB and the rest of the coordinate increment register bits at 0.

Most likely, the console doesn't display NBG0 or NBG1 if one of their coordinate increment is 0.

**Comment by BenjaminSiskoo** [comment] 2022-01-04 01:02
Kronos 2.2.0 du 03.10.2022
Mode OpenGL

![image](https://user-images.githubusercontent.com/12481242/147996157-9425e122-71bc-4a7f-bd5f-c4aedc1a874d.png)

Savestate : 
[MK-81304_000.zip](https://github.com/FCare/Kronos/files/7804757/MK-81304_000.zip)

**Comment by fafling** [comment] 2022-01-04 01:26
The problem is no longer the shadow, it's been fixed in may 2020.
The remaining issue is the title screen that shows the title immediately when it doesn't display on the console because the title layer has an illegal coordinate increment of 0.

**Closed as completed** 2022-01-04 10:51 UTC
