### ISSUE TITLE
Can't boot Games that were Patched by CDmage and converted to CHD

### ISSUE THREAD

**Issue by FuxorLuck** [FCare/Kronos#1029] opened 2021-05-18 11:24 UTC
Take any game and open the bin file with CDmage. Don't change anything in the game files and Press Save as
Now if you try to boot the game it will work but if you try to convert it to CHD and then boot, It won't work and you will be stuck on a black screen.
This issue isn't presented in Beetle Saturn emulator So I believe it's a problem with Kronos.

While it's true that I can use another program instead of CDmage a lot of Saturn homebrew and Patches for games uses CDmage.

**Comment by BenjaminSiskoo** [comment] 2021-05-18 11:34
thanks, François is busy for 2-3 months, do no quiet, it can take some time before resolving this bug. Nice report :)

**Comment by BenjaminSiskoo** [comment] 2021-05-19 09:44
@FuxorLuck the problem is with Kronos 2.1.5 public, it's fixed with the WIP, no available date to provide for now.

**Comment by FuxorLuck** [comment] 2021-05-23 09:59
@BenjaminSiskoo 
Glad to hear about that

**Comment by BenjaminSiskoo** [comment] 2021-05-23 10:01
Nice catch :)

**Closed as completed by BenjaminSiskoo** 2021-05-23 10:01 UTC
