### ISSUE TITLE
[Sonic Jam] Underwater Palette Bug

### ISSUE THREAD

**Issue by TheCommandoChicken** [FCare/Kronos#1526] opened 2024-02-29 21:13 UTC
What's the full name of the game (including region) ?
Sonic Jam (USA)

What's your frontend ? (standalone, libretro, ...) ?
Retroarch 1.17.0

What's your OS ? (windows, linux, OSX, ...) ?
Steam OS

What's your hardware ? (CPU, GPU, ...) ?
Steam Deck (Original Model)

What's the storage type of the game (official cd, burned cd or cd image) ?
CD Image

If applicable, what's the format of your cd image ? (cue/bin, ccd/img, iso, chd, ...)
.cue/.bin

Are you using any setting different from default ? If so, precise
Output to original resolution is on, no other setting has been changed.

If applicable, provide error messages, logs, screenshots, or whatever additional information that could help debugging this
Underwater stages have palette issues, where objects incorrectly use their above water palette if the camera isn't fully covered by water. Additionally the palette in the opening of Hydrocity Act 1 appears incorrect.
![Sonic Jam (USA)-240229-170046](https://github.com/FCare/Kronos/assets/62488159/01afe7ea-d546-43f6-b432-9495e8d8aa29)
![Sonic Jam (USA)-240229-170115](https://github.com/FCare/Kronos/assets/62488159/6cbdecc6-fbf5-4f84-aa59-7d891c5536c8)
![Sonic Jam (USA)-240229-170125](https://github.com/FCare/Kronos/assets/62488159/f9af890a-f7cc-49e6-820b-81d9080f8010)

**Comment by BenjaminSiskoo** [comment] 2024-02-29 22:12
Do you have a savestate ?

**Comment by TheCommandoChicken** [comment] 2024-03-01 21:49
Is one necessary? You should just be able to hop into any stage with water via the time attack. Assuming this can't be reproduced then it's probably an issue to do with my particular hardware.

**Comment by fafling** [comment] 2024-03-06 20:22
It's a duplicate of #695 .

**Closed as completed** 2024-08-27 08:04 UTC

**Comment by BenjaminSiskoo** [comment] 2024-08-27 13:44
Kronos Wip 26082024

![image](https://github.com/user-attachments/assets/2c101558-4146-47b2-80f2-8dd75e26d75c)

savestate : 

[MK-81079_001.zip](https://github.com/user-attachments/files/16762992/MK-81079_001.zip)
